# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-29 03:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_token', models.BigIntegerField(default=None)),
                ('number', models.IntegerField(default=None)),
                ('lat', models.FloatField(default=None)),
                ('lon', models.FloatField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='HelpGiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=30)),
                ('address', models.CharField(default=b'', max_length=100)),
                ('capacity', models.IntegerField(default=None)),
                ('lat', models.FloatField(default=None)),
                ('lon', models.FloatField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='IndividualDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=30)),
                ('age', models.IntegerField(default=None)),
                ('gender', models.BooleanField(default=None)),
                ('key', models.IntegerField(default=None)),
            ],
        ),
        migrations.AddField(
            model_name='groupdetails',
            name='individuals',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='disaster.IndividualDetails'),
        ),
    ]
