# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-29 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disaster', '0002_auto_20170129_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='data_token',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='person',
            name='disaster',
            field=models.CharField(default=b'', max_length=20),
        ),
    ]
